# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1531/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1531/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/workspace/projects/voxel-engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/workspace/projects/voxel-engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/snap/cmake/1531/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1531/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/snap/cmake/1531/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/snap/cmake/1531/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/snap/cmake/1531/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/snap/cmake/1531/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/snap/cmake/1531/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/snap/cmake/1531/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/workspace/projects/voxel-engine/CMakeFiles /home/user/workspace/projects/voxel-engine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/workspace/projects/voxel-engine/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/workspace/projects/voxel-engine/CMakeFiles /home/user/workspace/projects/voxel-engine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/workspace/projects/voxel-engine/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named VoxelEngine

# Build rule for target.
VoxelEngine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VoxelEngine
.PHONY : VoxelEngine

# fast build rule for target.
VoxelEngine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/build
.PHONY : VoxelEngine/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f lib/glfw/CMakeFiles/uninstall.dir/build.make lib/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f lib/glfw/src/CMakeFiles/glfw.dir/build.make lib/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f lib/glfw/src/CMakeFiles/update_mappings.dir/build.make lib/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

lib/glad/src/glad.o: lib/glad/src/glad.c.o
.PHONY : lib/glad/src/glad.o

# target to build an object file
lib/glad/src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/lib/glad/src/glad.c.o
.PHONY : lib/glad/src/glad.c.o

lib/glad/src/glad.i: lib/glad/src/glad.c.i
.PHONY : lib/glad/src/glad.i

# target to preprocess a source file
lib/glad/src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/lib/glad/src/glad.c.i
.PHONY : lib/glad/src/glad.c.i

lib/glad/src/glad.s: lib/glad/src/glad.c.s
.PHONY : lib/glad/src/glad.s

# target to generate assembly for a file
lib/glad/src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/lib/glad/src/glad.c.s
.PHONY : lib/glad/src/glad.c.s

src/engine.o: src/engine.cpp.o
.PHONY : src/engine.o

# target to build an object file
src/engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/engine.cpp.o
.PHONY : src/engine.cpp.o

src/engine.i: src/engine.cpp.i
.PHONY : src/engine.i

# target to preprocess a source file
src/engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/engine.cpp.i
.PHONY : src/engine.cpp.i

src/engine.s: src/engine.cpp.s
.PHONY : src/engine.s

# target to generate assembly for a file
src/engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/engine.cpp.s
.PHONY : src/engine.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/platform/camera.o: src/platform/camera.cpp.o
.PHONY : src/platform/camera.o

# target to build an object file
src/platform/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/platform/camera.cpp.o
.PHONY : src/platform/camera.cpp.o

src/platform/camera.i: src/platform/camera.cpp.i
.PHONY : src/platform/camera.i

# target to preprocess a source file
src/platform/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/platform/camera.cpp.i
.PHONY : src/platform/camera.cpp.i

src/platform/camera.s: src/platform/camera.cpp.s
.PHONY : src/platform/camera.s

# target to generate assembly for a file
src/platform/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/platform/camera.cpp.s
.PHONY : src/platform/camera.cpp.s

src/platform/renderer.o: src/platform/renderer.cpp.o
.PHONY : src/platform/renderer.o

# target to build an object file
src/platform/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/platform/renderer.cpp.o
.PHONY : src/platform/renderer.cpp.o

src/platform/renderer.i: src/platform/renderer.cpp.i
.PHONY : src/platform/renderer.i

# target to preprocess a source file
src/platform/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/platform/renderer.cpp.i
.PHONY : src/platform/renderer.cpp.i

src/platform/renderer.s: src/platform/renderer.cpp.s
.PHONY : src/platform/renderer.s

# target to generate assembly for a file
src/platform/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/platform/renderer.cpp.s
.PHONY : src/platform/renderer.cpp.s

src/platform/window.o: src/platform/window.cpp.o
.PHONY : src/platform/window.o

# target to build an object file
src/platform/window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/platform/window.cpp.o
.PHONY : src/platform/window.cpp.o

src/platform/window.i: src/platform/window.cpp.i
.PHONY : src/platform/window.i

# target to preprocess a source file
src/platform/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/platform/window.cpp.i
.PHONY : src/platform/window.cpp.i

src/platform/window.s: src/platform/window.cpp.s
.PHONY : src/platform/window.s

# target to generate assembly for a file
src/platform/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/platform/window.cpp.s
.PHONY : src/platform/window.cpp.s

src/utils/input_manager.o: src/utils/input_manager.cpp.o
.PHONY : src/utils/input_manager.o

# target to build an object file
src/utils/input_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/utils/input_manager.cpp.o
.PHONY : src/utils/input_manager.cpp.o

src/utils/input_manager.i: src/utils/input_manager.cpp.i
.PHONY : src/utils/input_manager.i

# target to preprocess a source file
src/utils/input_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/utils/input_manager.cpp.i
.PHONY : src/utils/input_manager.cpp.i

src/utils/input_manager.s: src/utils/input_manager.cpp.s
.PHONY : src/utils/input_manager.s

# target to generate assembly for a file
src/utils/input_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/utils/input_manager.cpp.s
.PHONY : src/utils/input_manager.cpp.s

src/utils/shader.o: src/utils/shader.cpp.o
.PHONY : src/utils/shader.o

# target to build an object file
src/utils/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/utils/shader.cpp.o
.PHONY : src/utils/shader.cpp.o

src/utils/shader.i: src/utils/shader.cpp.i
.PHONY : src/utils/shader.i

# target to preprocess a source file
src/utils/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/utils/shader.cpp.i
.PHONY : src/utils/shader.cpp.i

src/utils/shader.s: src/utils/shader.cpp.s
.PHONY : src/utils/shader.s

# target to generate assembly for a file
src/utils/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/utils/shader.cpp.s
.PHONY : src/utils/shader.cpp.s

src/world/chunk.o: src/world/chunk.cpp.o
.PHONY : src/world/chunk.o

# target to build an object file
src/world/chunk.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/world/chunk.cpp.o
.PHONY : src/world/chunk.cpp.o

src/world/chunk.i: src/world/chunk.cpp.i
.PHONY : src/world/chunk.i

# target to preprocess a source file
src/world/chunk.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/world/chunk.cpp.i
.PHONY : src/world/chunk.cpp.i

src/world/chunk.s: src/world/chunk.cpp.s
.PHONY : src/world/chunk.s

# target to generate assembly for a file
src/world/chunk.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/world/chunk.cpp.s
.PHONY : src/world/chunk.cpp.s

src/world/world_generator.o: src/world/world_generator.cpp.o
.PHONY : src/world/world_generator.o

# target to build an object file
src/world/world_generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/world/world_generator.cpp.o
.PHONY : src/world/world_generator.cpp.o

src/world/world_generator.i: src/world/world_generator.cpp.i
.PHONY : src/world/world_generator.i

# target to preprocess a source file
src/world/world_generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/world/world_generator.cpp.i
.PHONY : src/world/world_generator.cpp.i

src/world/world_generator.s: src/world/world_generator.cpp.s
.PHONY : src/world/world_generator.s

# target to generate assembly for a file
src/world/world_generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VoxelEngine.dir/build.make CMakeFiles/VoxelEngine.dir/src/world/world_generator.cpp.s
.PHONY : src/world/world_generator.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... VoxelEngine"
	@echo "... glad"
	@echo "... glfw"
	@echo "... lib/glad/src/glad.o"
	@echo "... lib/glad/src/glad.i"
	@echo "... lib/glad/src/glad.s"
	@echo "... src/engine.o"
	@echo "... src/engine.i"
	@echo "... src/engine.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/platform/camera.o"
	@echo "... src/platform/camera.i"
	@echo "... src/platform/camera.s"
	@echo "... src/platform/renderer.o"
	@echo "... src/platform/renderer.i"
	@echo "... src/platform/renderer.s"
	@echo "... src/platform/window.o"
	@echo "... src/platform/window.i"
	@echo "... src/platform/window.s"
	@echo "... src/utils/input_manager.o"
	@echo "... src/utils/input_manager.i"
	@echo "... src/utils/input_manager.s"
	@echo "... src/utils/shader.o"
	@echo "... src/utils/shader.i"
	@echo "... src/utils/shader.s"
	@echo "... src/world/chunk.o"
	@echo "... src/world/chunk.i"
	@echo "... src/world/chunk.s"
	@echo "... src/world/world_generator.o"
	@echo "... src/world/world_generator.i"
	@echo "... src/world/world_generator.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

